"""Admin endpoints for the integrated browser registration worker."""
from __future__ import annotations

import io
import os
import zipfile
from typing import Any

from fastapi import APIRouter, Depends, HTTPException, Request
from fastapi.responses import Response
from pydantic import BaseModel, Field, RootModel

from app.control.account.commands import AccountUpsert
from app.control.account.repository import AccountRepository
from app.control.registration.archive import ARCHIVE_EXT_KEY, encrypt_profile
from app.control.registration.cpa import cpa_auth_task_files, list_cpa_auth_tasks
from app.platform.auth.middleware import get_admin_key
from . import get_repo

router = APIRouter(prefix="/registration", tags=["Admin - Registration"])


class RegistrationSettingsRequest(RootModel[dict[str, Any]]):
    pass


class RegistrationArchiveItem(BaseModel):
    token: str = Field(min_length=1)
    email: str = ""
    password: str = ""
    oauth: dict[str, Any] = Field(default_factory=dict)
    provider: str = "grok_build"


def _manager(request: Request):
    manager = getattr(request.app.state, "registration_manager", None)
    if manager is None:
        raise HTTPException(503, "Registration runtime is not initialized")
    return manager


def _error(exc: Exception) -> HTTPException:
    return HTTPException(status_code=400, detail=str(exc))


@router.get("/config")
async def get_registration_config(request: Request):
    return _manager(request).get_settings()


@router.put("/config")
async def save_registration_config(req: RegistrationSettingsRequest, request: Request):
    try:
        return _manager(request).save_settings(req.root)
    except ValueError as exc:
        raise _error(exc) from exc


@router.get("/status")
async def registration_status(request: Request):
    return _manager(request).status()


class OutlookPoolResetRequest(BaseModel):
    scope: str = Field(default="all", pattern="^(retryable|failed|busy|invalid|used|unused|delete_invalid|all)$")


@router.get("/outlook-pool/details")
async def outlook_pool_details(provider_id: str, request: Request, status: str = "all"):
    try:
        return _manager(request).outlook_pool_details(provider_id, status)
    except ValueError as exc:
        raise _error(exc) from exc


@router.post("/outlook-pool/reset")
async def reset_outlook_pool(req: OutlookPoolResetRequest, request: Request):
    """Clear only local Microsoft mailbox-pool state; mailbox credentials remain local and masked."""
    try:
        return _manager(request).reset_outlook_pool(req.scope)
    except ValueError as exc:
        raise _error(exc) from exc


@router.post("/start")
async def start_registration(request: Request):
    try:
        port = int(os.getenv("SERVER_PORT", "8000"))
        return await _manager(request).start(admin_key=get_admin_key(), server_port=port)
    except (RuntimeError, ValueError) as exc:
        raise _error(exc) from exc


@router.post("/stop")
async def stop_registration(request: Request):
    try:
        return await _manager(request).stop()
    except RuntimeError as exc:
        raise _error(exc) from exc


@router.post("/archive/import")
async def import_registration_archives(
    items: list[RegistrationArchiveItem],
    request: Request,
    repo: AccountRepository = Depends(get_repo),
):
    """Store successful browser registrations with a Fernet-encrypted profile."""
    settings = _manager(request)._read_settings_raw()
    account = settings.get("account") or {}
    pool = str(account.get("pool") or "basic")
    tags = list(account.get("tags") or [])
    upserts: list[AccountUpsert] = []
    for item in items:
        token = item.token.strip()
        if not token:
            continue
        encrypted = encrypt_profile({
            "provider": item.provider or "grok_build",
            "email": item.email.strip(),
            "password": item.password,
            "oauth": item.oauth,
        })
        upserts.append(AccountUpsert(token=token, pool=pool, tags=tags, ext={ARCHIVE_EXT_KEY: encrypted}))
    if not upserts:
        raise HTTPException(400, "No valid registration archives provided")
    result = await repo.upsert_accounts(upserts)
    return {"count": result.upserted or len(upserts), "skipped": 0}


@router.get("/cpa-auths/tasks")
async def list_cpa_auth_export_tasks(request: Request):
    """Return task-isolated CPA export groups without exposing auth contents."""
    settings = _manager(request)._read_settings_raw()
    return {"items": list_cpa_auth_tasks(dict(settings.get("cpa") or {}))}


@router.get("/cpa-auths/export")
async def export_cpa_auths(task_id: str, request: Request):
    """Download CPA Auth JSON files generated by exactly one registration task."""
    selected_task = str(task_id or "").strip()
    if not selected_task:
        raise HTTPException(400, "task_id is required")
    settings = _manager(request)._read_settings_raw()
    try:
        files = cpa_auth_task_files(dict(settings.get("cpa") or {}), selected_task)
    except ValueError as exc:
        raise HTTPException(400, "invalid task_id") from exc
    if not files:
        raise HTTPException(404, "No CPA Auth JSON files found for this task")
    payload = io.BytesIO()
    with zipfile.ZipFile(payload, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for path in files:
            archive.write(path, arcname=path.name)
    safe_name = "".join(char if char.isalnum() or char in "_.-" else "_" for char in selected_task)
    headers = {"Content-Disposition": f'attachment; filename="grok2api-cpa-auths-{safe_name}.zip"'}
    return Response(content=payload.getvalue(), media_type="application/zip", headers=headers)


__all__ = ["router"]
